/** Generated by scripts/pixelate-favicon.mjs from deepseek-harness/apps/web/public/favicon.svg. */
export declare const PIXEL_FAVICON_GRID: string[];
export declare const PIXEL_FAVICON_FILLS: {
    readonly light: "#000000";
    readonly dark: "#ffffff";
};
