/** Generated by scripts/build.mjs — do not edit by hand. */
export declare const STRUCTURAL_PATCHES: {
    readonly inputBar: {
        readonly input: "ip6KuG_input";
        readonly mirror: "ip6KuG_mirror";
        readonly backdrop: "ip6KuG_backdrop";
        readonly card: "ip6KuG_card";
        readonly primary: "ip6KuG_primary";
    };
    readonly statsLine: {
        readonly root: "Lb3Jca_root";
        readonly sep: "Lb3Jca_sep";
    };
    readonly contextMeter: {
        readonly trigger: "_7ksPEG_trigger";
        readonly track: "_7ksPEG_track";
        readonly fill: "_7ksPEG_fill";
    };
};
