/**
 * Build the out-of-tree skin package against the adjacent DeepSeek Harness
 * checkout. The build has three generated inputs:
 *
 * 1. `src/client/font-data.ts` — the three embedded Fusion Pixel fonts.
 * 2. `src/client/literal-font-patches.ts` — exact CSS-Module class overrides
 *    for every component rule that still hard-codes a small `font-size`.
 *    Hashes are computed with the same lightningcss options the repository's
 *    client bundles use, so selectors stay scoped instead of guessing by the
 *    readable local class name.
 * 3. `src/client/pixel-favicon.ts` — official favicon pixelated at 32x32.
 * 4. `lib/client.js` — the shared tsdown client preset emits the
 *    `window.__ModuleLoader__.load` closure.
 */
import { readFile, writeFile, readdir } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { generatePixelFavicon } from './pixelate-favicon.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const harness = resolve(process.env.DSH_REPO ?? '../deepseek-harness')
const harnessRequire = createRequire(resolve(harness, 'package.json'))
const { transform } = harnessRequire('lightningcss')

async function base64(file) {
  return (await readFile(resolve(root, file))).toString('base64')
}

async function generateFontData() {
  const [mono, proportional, latin] = await Promise.all([
    base64('assets/fonts/fusion-pixel-12px-monospaced-sc.woff2'),
    base64('assets/fonts/fusion-pixel-12px-proportional-sc.woff2'),
    base64('assets/fonts/fusion-pixel-latin.woff2'),
  ])
  await writeFile(resolve(root, 'src/client/font-data.ts'), [
    '/** Generated by scripts/build.mjs — do not edit by hand. */',
    `export const FUSION_PIXEL_SC_WOFF2_BASE64 = '${mono}'`,
    `export const FUSION_PIXEL_PROPORTIONAL_SC_WOFF2_BASE64 = '${proportional}'`,
    `export const FUSION_PIXEL_LATIN_WOFF2_BASE64 = '${latin}'`,
    '',
  ].join('\n'))
}

const SIZE_MAP = { 10: 14, 11: 14, 12: 15, 13: 16, 14: 17, 15: 18, 16: 19 }

async function walkCss(dir) {
  const out = []
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name === 'lib' || entry.name === 'tests') continue
    const path = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...await walkCss(path))
    else if (entry.name.endsWith('.module.css')) out.push(path)
  }
  return out
}

function literalPatchesFor(css) {
  const out = []
  const blocks = [...css.matchAll(/([^{}]+)\{([^{}]*)\}/g)]
  for (const match of blocks) {
    const rawSelector = match[1].trim()
    if (rawSelector.startsWith('@') || rawSelector === 'from' || rawSelector === 'to') continue
    const body = match[2]
    const sizeMatch = body.match(/(?:^|;)font-size:(\d+)px/)
    if (sizeMatch === null) continue
    const oldSize = Number(sizeMatch[1])
    const newSize = SIZE_MAP[oldSize]
    if (newSize === undefined) continue
    const lineMatch = body.match(/(?:^|;)line-height:(\d+)px/)
    const declarations = [`font-size:${newSize}px!important`]
    if (lineMatch !== null) {
      const lineDelta = oldSize <= 11 ? 5 : 3
      declarations.push(`line-height:${Number(lineMatch[1]) + lineDelta}px!important`)
    }
    for (const selector of rawSelector.split(',')) {
      const trimmed = selector.trim()
      // Keep exactly the transformed module selectors that are class-based
      // and state-free. State selectors keep their own original size; the
      // base selector's override carries `!important` and wins when equal
      // specificity is not involved.
      if (trimmed !== '' && trimmed.includes('.') && /[>:+~]/.test(trimmed) === false) {
        out.push(`body[data-pixel-skin] ${trimmed}{${declarations.join(';')}}`)
      }
    }
  }
  return [...new Set(out)]
}

async function generateDistLiteralFontPatches() {
  const assetsDir = join(harness, 'apps/web/dist/assets')
  const entries = await readdir(assetsDir).catch(() => [])
  const files = entries.filter(file => /^index-.*\.css$/.test(file))
  if (files.length === 0) {
    throw new Error(
      'build: no apps/web dist CSS found — run `pnpm run build` in the harness checkout first',
    )
  }
  const patches = []
  for (const file of files) {
    patches.push(...literalPatchesFor(await readFile(join(assetsDir, file), 'utf8')))
  }
  return [...new Set(patches)]
}

async function generateLiteralFontPatches() {
  const roots = [
    join(harness, 'packages/client'),
    join(harness, 'packages/extensions/ui-cordis'),
  ]
  const files = []
  for (const cssRoot of roots) files.push(...await walkCss(cssRoot))
  const patches = []
  for (const file of files) {
    const result = transform({
      filename: file,
      code: await readFile(file),
      cssModules: { pattern: '[hash]_[local]' },
      minify: true,
    })
    patches.push(...literalPatchesFor(result.code.toString()))
  }
  // The web shell compiles source-aliased packages (ui-primitives,
  // ui-attachment, web-react, ...) through Vite, so their final class names
  // are `_[local]_[hash]`, not the `[hash]_[local]` names above. The built
  // index CSS is authoritative for those; merge its exact selectors too.
  patches.push(...await generateDistLiteralFontPatches())
  const unique = [...new Set(patches)]
  await writeFile(resolve(root, 'src/client/literal-font-patches.ts'), [
    '/** Generated by scripts/build.mjs — do not edit by hand. */',
    `export const LITERAL_FONT_PATCHES = ${JSON.stringify(unique.join('\n'))}`,
    '',
  ].join('\n'))
}

async function generateStructuralPatches() {
  const targets = [
    {
      key: 'inputBar',
      file: join(harness, 'packages/client/ui-conversation/src/client/skeleton/InputBar.module.css'),
      locals: ['input', 'mirror', 'backdrop', 'card', 'primary'],
    },
    {
      key: 'statsLine',
      file: join(harness, 'packages/client/ui-conversation/src/client/chat/StatsLine.module.css'),
      locals: ['root', 'sep'],
    },
    {
      key: 'contextMeter',
      file: join(harness, 'packages/client/ui-conversation/src/client/skeleton/ContextMeter.module.css'),
      locals: ['trigger', 'track', 'fill'],
    },
  ]
  const result = {}
  for (const target of targets) {
    const transformed = transform({
      filename: target.file,
      code: await readFile(target.file),
      cssModules: { pattern: '[hash]_[local]' },
      minify: true,
    })
    const classes = {}
    for (const local of target.locals) {
      const entry = transformed.exports?.[local]
      if (entry === undefined || entry.name === undefined) {
        throw new Error(`structural patch: missing ${local} in ${target.file}`)
      }
      classes[local] = entry.name
    }
    result[target.key] = classes
  }
  await writeFile(resolve(root, 'src/client/structural-patches.ts'), [
    '/** Generated by scripts/build.mjs — do not edit by hand. */',
    `export const STRUCTURAL_PATCHES = ${JSON.stringify(result, null, 2)} as const`,
    '',
  ].join('\n'))
}

await generateFontData()
await generateLiteralFontPatches()
await generatePixelFavicon()
await generateStructuralPatches()

const watch = process.argv.includes('--watch')
const run = (command, args) => {
  const result = spawnSync(command, args, { cwd: root, stdio: 'inherit' })
  if (result.error !== undefined) throw result.error
  if (result.status !== 0) process.exit(result.status ?? 1)
}

run(resolve(harness, 'node_modules/.bin/tsc'), ['-p', 'tsconfig.json'])
run(resolve(harness, 'node_modules/.bin/tsdown'), [
  '--env.DSH_BUILD_FACE=client',
  ...(watch ? ['--watch', '--ignore-watch', 'src/client/font-data.ts', '--ignore-watch', 'src/client/literal-font-patches.ts', '--ignore-watch', 'src/client/structural-patches.ts'] : []),
])
