/**
 * Pixelate the official DeepSeek Harness favicon.
 *
 * The original favicon is a smooth vector path. This script rasterizes it at
 * a small grid with sharp, applies a hard alpha threshold per cell, and emits
 * the result as:
 *
 * - `src/client/pixel-favicon.ts` — grid consumed by the browser plugin
 * - `assets/dsh-pixel-icon.svg` — repository/README logo
 *
 * The plugin preserves the official icon colors: black in light mode and
 * white in dark mode, matching the source SVG's own media query.
 */
import { createRequire } from 'node:module'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const harness = resolve(process.env.DSH_REPO ?? '../deepseek-harness')

const SOURCE_FAVICON = join(harness, 'apps/web/public/favicon.svg')
const TARGET_SIZE = 32
const ALPHA_THRESHOLD = 128
const BODY = 'B'
const FILL_LIGHT = '#000000'
const FILL_DARK = '#ffffff'

async function loadSharp() {
  // Prefer a local installation (npm install in this repo), then fall back
  // to the adjacent harness checkout's pnpm store.
  try {
    const localRequire = createRequire(resolve(root, 'package.json'))
    return localRequire('sharp')
  } catch {
    const pnpmRoot = join(harness, 'node_modules/.pnpm')
    const candidates = await readdir(pnpmRoot)
    const sharpDir = candidates.find(name => name.startsWith('sharp@'))
    if (sharpDir === undefined) {
      throw new Error('pixelate-favicon: sharp not found in this repo or the harness checkout')
    }
    const sharpRoot = resolve(pnpmRoot, sharpDir, 'node_modules/sharp')
    const harnessRequire = createRequire(resolve(sharpRoot, 'package.json'))
    return harnessRequire('sharp')
  }
}

async function rasterizeGrid() {
  const sharp = await loadSharp()
  const svg = await readFile(SOURCE_FAVICON)
  const rgba = await sharp(svg, { density: 72 })
    .resize(TARGET_SIZE, TARGET_SIZE, { fit: 'fill', kernel: 'nearest' })
    .ensureAlpha()
    .raw()
    .toBuffer()

  const rows = []
  for (let y = 0; y < TARGET_SIZE; y += 1) {
    let row = ''
    for (let x = 0; x < TARGET_SIZE; x += 1) {
      const alpha = rgba[(y * TARGET_SIZE + x) * 4 + 3]
      row += alpha >= ALPHA_THRESHOLD ? BODY : ' '
    }
    rows.push(row)
  }
  return rows
}

function rowsToSvg(rows, fill) {
  const rects = []
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length; x += 1) {
      if (row[x] === BODY) {
        rects.push(`<rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`)
      }
    }
  })
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${TARGET_SIZE} ${TARGET_SIZE}" width="128" height="128" shape-rendering="crispEdges">${rects.join('')}</svg>`
}

export async function generatePixelFavicon() {
  const rows = await rasterizeGrid()
  const gridText = rows.map(row => `  '${row}',`).join('\n')
  await writeFile(resolve(root, 'src/client/pixel-favicon.ts'), [
    '/** Generated by scripts/pixelate-favicon.mjs from deepseek-harness/apps/web/public/favicon.svg. */',
    'export const PIXEL_FAVICON_GRID = [',
    gridText,
    ']',
    '',
    'export const PIXEL_FAVICON_FILLS = {',
    `  light: '${FILL_LIGHT}',`,
    `  dark: '${FILL_DARK}',`,
    '} as const',
    '',
  ].join('\n'))
  await writeFile(resolve(root, 'assets/dsh-pixel-icon.svg'), `${rowsToSvg(rows, FILL_LIGHT)}\n`)
}

const isMain = process.argv[1] !== undefined
  && process.argv[1].endsWith('pixelate-favicon.mjs')

if (isMain) {
  await generatePixelFavicon()
  console.log(`pixelate-favicon: ${TARGET_SIZE}x${TARGET_SIZE} favicon generated`)
}
