/** Generated by scripts/build.mjs — do not edit by hand. */
export const STRUCTURAL_PATCHES = {
  "inputBar": {
    "input": "ip6KuG_input",
    "mirror": "ip6KuG_mirror",
    "backdrop": "ip6KuG_backdrop",
    "card": "ip6KuG_card",
    "primary": "ip6KuG_primary"
  },
  "statsLine": {
    "root": "Lb3Jca_root",
    "sep": "Lb3Jca_sep"
  },
  "contextMeter": {
    "trigger": "_7ksPEG_trigger",
    "track": "_7ksPEG_track",
    "fill": "_7ksPEG_fill"
  }
} as const
